import { Light } from './light';

export const LIGHTS: Light[] = [
    { on: false, color: 'blue', letter: 'A', path: './../../../assets/blue.svg'},
    { on: false, color: 'red', letter: 'B', path: './../../../assets/red.svg'},
    { on: false, color: 'white', letter: 'C', path: './../../../assets/white.svg'},
    { on: false, color: 'yellow', letter: 'D', path: './../../../assets/yellow.svg'},
    { on: false, color: 'green', letter: 'E', path: './../../../assets/green.svg'},
    { on: false, color: 'blue', letter: 'F', path: './../../../assets/blue.svg'},
    { on: false, color: 'red', letter: 'G', path: './../../../assets/red.svg'},
    { on: false, color: 'white', letter: 'H', path: './../../../assets/white.svg'},
    { on: false, color: 'yellow', letter: 'I', path: './../../../assets/yellow.svg'},
    { on: false, color: 'green', letter: 'J', path: './../../../assets/green.svg'},
    { on: false, color: 'blue', letter: 'K', path: './../../../assets/blue.svg'},
    { on: false, color: 'red', letter: 'L', path: './../../../assets/red.svg'},
    { on: false, color: 'white', letter: 'M', path: './../../../assets/white.svg'},
    { on: false, color: 'yellow', letter: 'N', path: './../../../assets/yellow.svg'},
    { on: false, color: 'green', letter: 'O', path: './../../../assets/green.svg'},
    { on: false, color: 'blue', letter: 'P', path: './../../../assets/blue.svg'},
    { on: false, color: 'red', letter: 'Q', path: './../../../assets/red.svg'},
    { on: false, color: 'white', letter: 'R', path: './../../../assets/white.svg'},
    { on: false, color: 'yellow', letter: 'S', path: './../../../assets/yellow.svg'},
    { on: false, color: 'green', letter: 'T', path: './../../../assets/green.svg'},
    { on: false, color: 'blue', letter: 'U', path: './../../../assets/blue.svg'},
    { on: false, color: 'red', letter: 'V', path: './../../../assets/red.svg'},
    { on: false, color: 'white', letter: 'W', path: './../../../assets/white.svg'},
    { on: false, color: 'yellow', letter: 'X', path: './../../../assets/yellow.svg'},
    { on: false, color: 'green', letter: 'Y', path: './../../../assets/green.svg'},
    { on: false, color: 'blue', letter: 'Z', path: './../../../assets/blue.svg'},
]